totalRoundCurrencyAmount:
  matchPointTotal: 50
totalMultiple:
  matchPointTotal: 25
  multiple: 0.25
everyXItems:
  matchPointTotal: 5
  xItems: 2
itemDescriptionLengthMultiple:
  multiple: 3
  priceMultiplier: 0.2
purchaseDateParity:
  matchPointTotal: 6
purchaseTimeRange:
  matchPointTotal: 10
  hours: 
    start: 14
    end: 16
  minutes:
    start: 1
    end: 0
global:
  defaultPoints: 0